# =============================================================================
# R/reporting.R — metadata stamping, CSV/TeX/MD writers, theory table, figure data.
# Tables are auto-generated from CSVs (never hand-edited); write_tex prepends a
# do-not-edit banner. Ported write_tex idiom from PMM3_vs_MLE-TN/scripts/07.
# =============================================================================

cfg_stamp <- function(df) {
  ps <- phase_settings(); gm <- g_mode_spec()
  df$est_version <- CFG$est_version; df$phase <- ps$phase; df$g_mode <- gm$name
  df$reps <- ps$reps; df$test_n <- ps$test_n; df$B_boot <- ps$B_boot
  df$delta_main <- CFG$delta_main; df$seed_base <- CFG$seed_base
  df$generated <- CFG$artifact_stamp
  df
}

write_csv_stamped <- function(df, name, stamp = TRUE) {
  ensure_dirs()
  if (stamp) df <- cfg_stamp(df)
  path <- file.path(CFG$paths$results, name)
  utils::write.csv(df, path, row.names = FALSE)
  message("  wrote ", path)
  invisible(path)
}

write_tex <- function(df, name, caption = "", label = "", digits = 3, align = NULL,
                      fit_width = FALSE) {
  ensure_dirs()
  path <- file.path(CFG$paths$tables, name)
  # escape=FALSE lets math headers ($g_2$) render; escape _/%/&/# only OUTSIDE math
  # spans (strings without a '$'), so plain headers/cells (RTE_CV, dataset_id) compile.
  texsafe <- function(x) ifelse(grepl("\\$", x), x, gsub("([_%&#])", "\\\\\\1", x))
  names(df) <- texsafe(names(df))
  for (j in seq_along(df)) if (is.character(df[[j]])) df[[j]] <- texsafe(df[[j]])
  tab <- knitr::kable(df, format = "latex", booktabs = TRUE, digits = digits,
                      escape = FALSE, caption = caption, label = label, align = align,
                      linesep = "", row.names = FALSE)
  txt <- as.character(tab)
  # fit_width=TRUE wraps the tabular in \resizebox{\textwidth}{!}{..} so a too-wide
  # table (many columns / long CI strings) scales down to the text block instead of
  # overflowing the right margin. The caption stays full size; numbers are unchanged.
  if (isTRUE(fit_width)) {
    txt <- sub("\\begin{tabular}", "\\resizebox{\\textwidth}{!}{%\n\\begin{tabular}",
               txt, fixed = TRUE)
    txt <- sub("\\end{tabular}", "\\end{tabular}}", txt, fixed = TRUE)
  }
  con <- file(path, open = "wt"); on.exit(close(con))
  writeLines(c(sprintf("%% Auto-generated by PMM-RTE (v%s, %s) — do not edit manually.",
                       CFG$est_version, CFG$artifact_stamp),
               txt), con)
  message("  wrote ", path)
  invisible(path)
}

normalize_pdf_metadata <- function(path) {
  if (!file.exists(path)) return(invisible(path))
  x <- readBin(path, what = "raw", n = file.info(path)$size)
  stamp <- charToRaw("D:20260629000000")
  if (length(x) >= length(stamp)) {
    for (i in seq_len(length(x) - length(stamp) + 1L)) {
      z <- as.integer(x[i:(i + length(stamp) - 1L)])
      if (z[1L] == 68L && z[2L] == 58L && all(z[3L:16L] >= 48L & z[3L:16L] <= 57L)) {
        x[i:(i + length(stamp) - 1L)] <- stamp
      }
    }
  }
  writeBin(x, path)
  invisible(path)
}

# Table 2: theoretical PMM efficiency factors per error family
build_theory_factor_table <- function(catalog) {
  tab <- catalog[, c("family", "gamma3", "gamma4", "gamma6", "g2", "g3",
                     "var_reduction_pmm2", "var_reduction_pmm3")]
  names(tab) <- c("Distribution", "$\\gamma_3$", "$\\gamma_4$", "$\\gamma_6$",
                  "$g_2$", "$g_3$", "$1-g_2$", "$1-g_3$")
  tab
}

# Figure 1 data: eigenbasis shrinkage s_j(lambda; k,g) over a lambda axis
emit_eigen_curve <- function(kg = list(c(0.1, 0), c(1, 0), c(1, 1), c(10, 1)),
                             lambda = 10^seq(-2, 3, length.out = 120)) {
  rows <- lapply(kg, function(z) {
    k <- z[1]; g <- z[2]
    data.frame(k = k, g = g, lambda = lambda,
               s = lambda * (lambda + g) / ((lambda + 1) * (lambda + k)),
               stringsAsFactors = FALSE)
  })
  do.call(rbind, rows)
}

# Figure 2/3 data from a synthetic summary (PMM-RTE deployable variant)
emit_tradeoff_data <- function(summary, target = "PMM2_RTE_Stable") {
  s <- summary[summary$method == target, , drop = FALSE]
  data.frame(scenario_id = s$scenario_id, rho = s$rho, error = s$error,
             beta_mse_ratio_rtecv = s$ratio_rtecv_med,
             test_rmse = s$median_test_rmse, trace_var_slope = s$trace_var_slope,
             stringsAsFactors = FALSE)
}

# Representative high-collinearity cells (same selection as the tables' main_cells):
# max p, at the small-n/extreme-rho corner and the large-n/mild-rho corner.
rep_cells <- function(s) {
  sel <- s$p == max(s$p, na.rm = TRUE) &
    ((s$n == min(s$n, na.rm = TRUE) & s$rho == max(s$rho, na.rm = TRUE)) |
     (s$n == max(s$n, na.rm = TRUE) & s$rho == min(s$rho, na.rm = TRUE)))
  if (any(sel)) s[sel, ] else s
}

# Forest plot of the paired beta-MSE ratio to RTE_CV (log x, point = median, bar = 95%
# CI), one panel per error family x regime. Replaces a dense synthetic table: the
# PMM-vs-RTE_Stable gap and the Gaussian fallback read at a glance. hi_method is drawn
# red (the deployable PMM-RTE headline); RTE_CV (ratio 1) is the blue reference.
emit_forest_pdf <- function(summary, methods, hi_method, fams, file) {
  s <- rep_cells(summary[summary$method %in% methods, , drop = FALSE])
  fams <- fams[fams %in% s$error]
  regimes <- unique(s[, c("n", "rho")]); regimes <- regimes[order(regimes$n, -regimes$rho), ]
  mlev <- rev(methods)
  path <- file.path(CFG$paths$figures, file)
  grDevices::pdf(path,
                 width = 4.4 * nrow(regimes), height = 1.05 * length(fams) * length(mlev) / 3 + 0.6)
  on.exit({ grDevices::dev.off(); normalize_pdf_metadata(path) })
  graphics::par(mfrow = c(length(fams), nrow(regimes)), mar = c(3.1, 8.3, 1.8, 0.8),
                mgp = c(1.9, 0.6, 0), cex = 0.9)
  for (fam in fams) for (ri in seq_len(nrow(regimes))) {
    rg <- regimes[ri, ]
    d <- s[s$error == fam & s$n == rg$n & s$rho == rg$rho, ]
    d <- d[match(mlev, d$method), ]
    xr <- range(c(d$ratio_rtecv_lo, d$ratio_rtecv_hi, 1), na.rm = TRUE)
    plot(NA, xlim = xr, ylim = c(0.5, length(mlev) + 0.5), log = "x", yaxt = "n",
         xlab = expression("ratio of " * beta * "-MSE to RTE"[CV] * "  (log scale)"), ylab = "",
         main = bquote(.(fam) * ":  " * list(italic(n) == .(rg$n), rho == .(rg$rho))),
         cex.main = 0.98)
    graphics::abline(v = 1, lty = 2, col = "grey50")
    col <- ifelse(mlev == hi_method, "firebrick",
           ifelse(mlev == "RTE_CV", "steelblue", "grey20"))
    lwd <- ifelse(mlev == hi_method, 2.6, 1.3)
    graphics::segments(d$ratio_rtecv_lo, seq_along(mlev), d$ratio_rtecv_hi, seq_along(mlev),
                       col = col, lwd = lwd)
    graphics::points(d$ratio_rtecv_med, seq_along(mlev), pch = 19, col = col,
                     cex = ifelse(mlev == hi_method, 1.35, 1.0))
    graphics::axis(2, at = seq_along(mlev), labels = mlev, las = 1, cex.axis = 0.88,
                   font = ifelse(mlev == hi_method, 2, 1))
  }
  invisible(file)
}

# Real-data coefficient stability as a lollipop/dot plot (log x = slope-variance trace,
# lower = more stable), one panel per dataset x scale. red = PMM-RTE headline,
# blue = RTE_CV reference. Replaces the wide real-data table in the main text.
emit_realdata_pdf <- function(rsum, methods, file) {
  dsets <- unique(rsum$dataset_id); scales <- c("raw", "log1p")
  scales <- scales[scales %in% rsum$scale]
  mlev <- rev(methods)
  path <- file.path(CFG$paths$figures, file)
  grDevices::pdf(path,
                 width = 3.6 * length(dsets), height = 1.5 * length(scales) + 0.8)
  on.exit({ grDevices::dev.off(); normalize_pdf_metadata(path) })
  graphics::par(mfrow = c(length(scales), length(dsets)), mar = c(3.2, 8.0, 1.8, 0.8),
                mgp = c(1.9, 0.6, 0), cex = 0.9)
  for (sc in scales) for (ds in dsets) {
    d <- rsum[rsum$dataset_id == ds & rsum$scale == sc, ]
    d <- d[match(mlev, d$method), ]
    v <- d$slope_var_trace; v[is.na(v) | v <= 0] <- NA
    xr <- range(v, na.rm = TRUE)
    plot(NA, xlim = xr, ylim = c(0.5, length(mlev) + 0.5), log = "x", yaxt = "n",
         xlab = "slope-variance trace  (log scale)", ylab = "",
         main = sprintf("%s,  %s", ds, sc), cex.main = 0.95)
    col <- ifelse(grepl("PMM[0-9]_RTE_Stable", mlev), "firebrick",
           ifelse(mlev == "RTE_CV", "steelblue", "grey30"))
    graphics::segments(xr[1], seq_along(mlev), v, seq_along(mlev), col = col, lwd = 1.2)
    graphics::points(v, seq_along(mlev), pch = 19, col = col,
                     cex = ifelse(col == "firebrick", 1.35, 1.05))
    graphics::axis(2, at = seq_along(mlev), labels = mlev, las = 1, cex.axis = 0.85,
                   font = ifelse(col == "firebrick", 2, 1))
  }
  invisible(file)
}

# Compact markdown report (quick human reading, not the manuscript)
write_md_report <- function(summary, covtransfer, block, name) {
  ensure_dirs()
  ps <- phase_settings(); gm <- g_mode_spec()
  path <- file.path(CFG$paths$results, name)
  con <- file(path, open = "wt"); on.exit(close(con))
  wl <- function(...) writeLines(sprintf(...), con)
  wl("# PMM-RTE synthetic MC report — block %s", block)
  writeLines("", con)
  wl("Generated: %s | phase=%s reps=%d test_n=%d B_boot=%d | g_mode=%s | seed=%d | v%s",
     CFG$artifact_stamp, ps$phase, ps$reps, ps$test_n,
     ps$B_boot, gm$name, CFG$seed_base, CFG$est_version)
  writeLines("", con)
  for (sid in unique(summary$scenario_id)) {
    b <- summary[summary$scenario_id == sid, , drop = FALSE]
    wl("## %s", sid); writeLines("", con)
    writeLines("| method | median beta-MSE | paired /RTE_CV [95% CI] (p) | trace Var(beta) | sign-flip | boundary g-frac | med g | ok |", con)
    writeLines("|---|---:|---|---:|---:|---:|---:|---:|", con)
    for (i in seq_len(nrow(b))) {
      writeLines(sprintf("| %s | %.5g | %.3f [%.3f, %.3f] (%.1e) | %.4g | %.3f | %.2f | %s | %.2f |",
        b$method[i], b$median_beta_mse[i], b$ratio_rtecv_med[i], b$ratio_rtecv_lo[i],
        b$ratio_rtecv_hi[i], b$ratio_rtecv_p[i], b$trace_var_slope[i], b$sign_flip_rate[i],
        b$boundary_hit_frac[i],
        ifelse(is.na(b$median_g[i]), "NA", formatC(b$median_g[i], format = "fg", digits = 2)),
        b$ok_rate[i]), con)
    }
    writeLines("", con)
  }
  if (!is.null(covtransfer) && nrow(covtransfer)) {
    wl("## Proposition-2 covariance transfer (fixed k=%.2g, g=%.2g; benign/asymptotic scenarios)",
       covtransfer$k_fixed[1], covtransfer$g_fixed[1]); writeLines("", con)
    writeLines("| scenario | raw Cov(PMM)/Cov(OLS) | transferred ratio | empirical g_S |", con)
    writeLines("|---|---:|---:|---:|", con)
    for (i in seq_len(nrow(covtransfer)))
      writeLines(sprintf("| %s | %.3f | %.3f | %.3f |", covtransfer$scenario_id[i],
        covtransfer$raw_cov_ratio[i], covtransfer$transferred_cov_ratio[i],
        covtransfer$gS_emp[i]), con)
    writeLines("", con)
  }
  message("  wrote ", path)
  invisible(path)
}
